### ISSUE TITLE
proxy_1 is not defined when CLIENTS = 1

### ISSUE THREAD

**Issue by artemii235** [tonymorony/scaling_tests_project#2]
`docker run -p 127.0.0.1:7000:7000 -e CLIENTS=1 -e CHAIN=ticker -e TEST_ADDY=R9imXLs1hEcU9KbFDQq2hJEEJ1P5UoekaF -e TEST_WIF=UqqW7f766rADem9heD8vSBvvrdfJb3zg5r8du9rJxPtccjWf7RG9 -e TEST_PUBKEY=021607076d7a2cb148d542fb9644c04ffc22d2cca752f80755a0402a24c567b17a "-v" "/home/artem/.zcash-params:/root/.zcash-params" artempikulin/testblockchain`
Results into
```
Traceback (most recent call last):
  File "/start_blockchain.py", line 67, in <module>
    proxy_1.generate(1)
NameError: name 'proxy_1' is not defined
```

**Comment by artemii235** [comment]
Locally I've used the `proxy_0.generate(1)` fix but maybe you'd like to create another solution so I haven't created the PR.

**Comment by tonymorony** [comment]
fixed by https://github.com/tonymorony/scaling_tests_project/commit/39eff011c9cb4021530d568087fba902b02504bc

**Comment by tonymorony** [comment]
thank you for issue @artemii235 ! :)
